version: '3.6'

services:
  nginx: 
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-net

  node:
    image: rovilarino/node:app-node
    # build: 
    #   context: ./node
    #   dockerfile: Dockerfile
    container_name: node-app
    command: node index.js;
    restart: always
    tty: true
    networks:
      - app-net

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycledb
      - MYSQL_ROOT_PASSWORD=fullcyclepass
    networks:
      - app-net


networks:
  app-net:
    driver: bridge